# Generated by Django 5.0.6 on 2024-05-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signature/'),
        ),
    ]
